### ISSUE TITLE
Customize app theme

### ISSUE THREAD

**Issue by AlonDiskin** [AlonDiskin/AppsBrowser#3]
In order to customize app visual appearance to my liking
As the user
I want to set the be able to change the app theme

- [x] provide day, night, and auto(time dependent) themes
- [x] change theme off whole app at runtime
- [x] day theme should be the default one for the app
